### register-jurjen
POST {{host}}/api/user
Content-Type: application/json

{
  "email": "jurjen@vorhauer.nl",
  "name": "Jurjen",
  "password": "password",
  "born": "1967-03-01"
}

### login-jurjen
POST {{host}}/api/login
Content-Type: application/json

{
  "username": "jurjen@vorhauer.nl",
  "password": "password"
}

> {% client.global.set("authorized", response.body); %}

### register-frodo
POST {{host}}/api/user
Content-Type: application/json

{
  "email":"frodo@baggins.me","name":"Frodo","password":"password","born":"2016-09-15"
}

### register-random
POST {{host}}/api/user
Content-Type: application/json

{
  "email": "{{$random.email}}",
  "name": "{{$random.alphabetic(13)}}",
  "password": "{{$random.alphanumeric(11)}}",
  "born": "{{$random.integer(1900,2010)}}-0{{$random.integer(0,10)}}-{{$random.integer(10,28)}}"
}

### get-all-users
GET {{host}}/api/users

### get-by-id
GET {{host}}/api/user/id/f702e417-c0f1-45ca-814c-e346304f0a95

### get-by-email
GET {{host}}/api/user/email/jurjen@vorhauer.nl

### post-new-note
POST {{host}}/api/note
Content-Type: application/json
X-Auth: {{authorized}}

{
  "user": "39260243-6305-4898-b03a-6ce880894931",
  "title": "Jurjen's second Note",
  "body": "Note taking in its simplest form :-)"
}
