### register-jurjen
POST {{host}}/api/users
Content-Type: application/json
Accept: application/json

{"email": "jurjen@vorhauer.nl", "name": "Jurjen", "password": "password"}

### get-all-users
GET {{host}}/api/users

### get-one-user
GET {{host}}/api/users/545930050313572977

### login-jurjen
POST {{host}}/api/login
Content-Type: application/json

{"username": "jurjen@vorhauer.nl", "password": "password"}

> {% client.global.set("authorized", response.body.token); %}

### get-me
GET {{host}}/api/users/me
Authorization: Bearer {{authorized}}

### get-my-notes
GET {{host}}/api/users/notes
Authorization: Bearer {{authorized}}

### get-my-tasks
GET {{host}}/api/users/tasks
Authorization: Bearer {{authorized}}

### post-new-note
POST {{host}}/api/notes
Content-Type: application/json
Authorization: Bearer {{authorized}}

{
  "title": "My Second Note",
  "body": "More notes is just better!"
}

### get-all-notes
GET {{host}}/api/notes
Authorization: Bearer {{authorized}}

### post-new-task
POST {{host}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{authorized}}

{
  "title": "Make Vault story",
  "body": "In order to deploy to production, we need to store secrets in the <strong>Vault</strong>",
  "due": "2024-03-01T09:00:00"
}

### get-liveness
GET {{host}}/info/alive

### get-readiness
GET {{host}}/info/ready

### get-counts
GET {{host}}/info/counts

### get-one-task
GET {{host}}/api/tasks/545930282606711300
Authorization: Bearer {{authorized}}
