spring:
  config:
    name: KoNoMaS
  aop:
    proxy-target-class: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
    info:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    cassandra:
      enabled: false
