apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: noviblog
  name: noviblog
spec:
  template:
    metadata:
      labels:
        app: noviblog
    spec:
      containers:
        - name: noviblog
          image: ghcr.io/jvorhauer/noviblog:latest
          env:
            - name: ASTRA_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: astra-config
                  key: ASTRA_USERNAME
            - name: ASTRA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: astra-config
                  key: ASTRA_PASSWORD
            - name: ASTRA_SCB
              value: /var/local/scb_e93d3b60-4128-4094-8824-a37327f973c4_europe-west1.zip
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
            requests:
              cpu: 500m
              memory: "512Mi"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              port: 8080
              path: /actuator/health/liveness
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 5
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - name: noviblog
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/local
              name: astra-scb
              readOnly: true
      imagePullSecrets:
        - name: dockerregistry
      volumes:
        - name: astra-scb
          secret:
            secretName: astra-scb
  selector:
    matchLabels:
      app: noviblog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
