name: build
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    env:
      KONOMAS_JWT_SECRET: ${{ secrets.KONOMAS_JWT_SECRET }}
      KONOMAS_SENTRY_DSN: ${{ secrets.KONOMAS_SENTRY_DSN }}
      KONOMAS_SENTRY_TOKEN: ${{ secrets.KONOMAS_SENTRY_TOKEN }}
      ASTRA_SCB: ${{ secrets.ASTRA_SCB }}
      ASTRA_USERNAME: ${{ secrets.ASTRA_USERNAME }}
      ASTRA_PASSWORD: ${{ secrets.ASTRA_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build jacocoTestReport
          gradle-version: 8.6
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
