name: release
on:
  push:
    branches: [ "release" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Release
        uses: gradle/gradle-build-action@v3
        with:
          arguments: release -Prelease.useAutomaticVersion=true
